import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="font-bold text-7xl mb-3 ">
          Welcome to{" "}
          <a
            href="https://nextjs.org"
            className="bg-gradient-to-r from-teal-300 to-blue-300 bg-clip-text text-transparent "
          >
            Next.js!
          </a>
        </h1>

        <p className="font-normal text-2xl">
          Get started by editing{" "}
          <code className="font-mono bg-gray-100 px-2 py-1">
            pages/index.js
          </code>
        </p>

        <div className="flex flex-wrap max-w-screen-md justify-center items-center">
          <Card />
          <Card />
          <Card />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
