import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="font-bold text-7xl mb-3 ">
          Welcome to{" "}
          <a
            href="https://nextjs.org"
            className="bg-gradient-to-r from-teal-300 to-blue-300 bg-clip-text text-transparent "
          >
            Next.js!
          </a>
        </h1>

        <p className="font-normal text-2xl">
          Get started by editing{" "}
          <code className="font-mono bg-gray-100 px-2 py-1">
            pages/index.js
          </code>
        </p>

        <div className="flex flex-wrap max-w-screen-md justify-center items-center">
          <a
            href="https://nextjs.org/docs"
            className="m-4 p-6 border-[1px] max-w-[45%] border-gray-200 rounded-xl hover:border-blue-600 hover:text-blue-600"
          >
            <h2 className="text-2xl mb-4">Documentation &rarr;</h2>
            <p className="text-xl">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
